#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# bspwm directory
DIR="$HOME/.config/scripts"

# rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/rofi_askpass

# execute the application
sudo -A $1
