#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

CONFIG="$HOME/.config"

# fix padding
bspc config bottom_padding 0
bspc config top_padding 0

# launch polybar
bash "$CONFIG"/polybar/polybar.sh
